config/routes.rb
Rails.application.routes.draw do
  	root to: "home#index"

  	resources :users, only: [:new, :create, :update, :destroy]

  	scope path: 'session/' do
  		get 'new', as: 'new_session', to: 'session#new'
  		post 'create', as: 'create_session', to: 'session#create'
  		delete 'delete', as: 'delete_session', to: 'session#destroy'
 	end

  	scope path: 'user/', as: 'user' do
  		resources :todos, only: [:index, :new, :create, :update, :destroy]
  		patch '/todo/:id/up', as: 'todo_up', to: 'todos#up_in_list'
  		patch '/todo/:id/down', as: 'todo_down', to: 'todos#down_in_list'
      patch '/todo/:id/done', as: 'todo_done', to: 'todos#done'
  	end
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true

  belongs_to :user

  scope :sorted, -> { order(priority: :asc) }
  scope :done, -> { where(status: 1) }
  scope :not_done, -> { where(status: 0) }

  before_create :set_priority, :set_status

  private def set_priority
  	if (self.user)
  		max_priority = self.user.todos.maximum(:priority)
  		self.priority = max_priority ? max_priority + 1 : 1
  	else
  		self.priority = 0
  	end
  end

  private def set_status
    self.status = 0
  end

  private def previous_todo
    self.user.todos.sorted.where(status: self.status).where("priority < ?", self.priority).last
  end

  private def next_todo
    self.user.todos.sorted.where(status: self.status).where("priority > ?", self.priority).first
  end

  def mark_done
    self.update(status: 1)
  end

  def mark_not_done
    self.update(status: 0)
  end

  def is_first
    todo_above = previous_todo
    return todo_above == nil
  end

  def is_last
    todo_under = next_todo
    return todo_under == nil
  end

  def up_in_users_list
  	todo_above = previous_todo
    if todo_above
      above_priority = todo_above.priority
  	  todo_above.update(priority: self.priority)
  	  self.update(priority: above_priority)
    end
  end

  def down_in_users_list
  	todo_under = next_todo
    if todo_under
      under_priority = todo_under.priority
  	  todo_under.update(priority: self.priority)
  	  self.update(priority: under_priority)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, uniqueness: true

	has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def current_user
    	User.find_by(id: session[:user_id])
	end

	def authenticate_user
	   	redirect_to new_session_path unless current_user != nil
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to user_todos_url
  	end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.find_by(email: params[:email])
   	if @user
      	session[:user_id] = @user.id
      	redirect_to user_todos_path
   	else
        @user = User.new
        @error = "This account does not exist"
      	render 'new'
   	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user

  def index
    @todos = current_user.todos.not_done.sorted
  end

  def done
    @todos = current_user.todos.done.sorted
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(params.require(:todo).permit(:title, :description, :due_date))
    @todo.user = current_user
    @todo.save

    if @todo.errors.any?
      render 'new'
    else
      redirect_to user_todos_path
    end
  end

  def update
  end

  def up_in_list
    @todo = Todo.find_by(id: params[:id])
    @todo.up_in_users_list
    redirect_to user_todos_path
  end

  def down_in_list
    @todo = Todo.find_by(id: params[:id])
    @todo.down_in_users_list
    redirect_to user_todos_path
  end

  def done
    @todo = Todo.find_by(id: params[:id])
    @todo.mark_done
    redirect_to user_todos_path
  end

  def destroy
    @todo = Todo.find_by(id: params[:id])
    @todo.destroy
    redirect_to user_todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.create(params.require(:user).permit(:email))
    if @user.errors.any?
      render 'new'
    else
      session[:user_id] = @user.id
      redirect_to user_todos_path
    end
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h1>My todo !</h1>
<p>Login or signup to manage your todolist</p>
<%= link_to "Log in", new_session_path %><br/>
<%= link_to "Sign up", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTodolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<%= link_to 'Back', root_path %>

<div class="error">
	<%= @error %>
</div>

<h1>Log in</h1>
<%= form_tag create_session_url do %>
<%= label_tag :email %>
<%= email_field_tag :email %>
<%= submit_tag "Login"%>
<% end %>

app/views/todos/_form.html.erb
<div class="error">
	<% @todo.errors.each do |attr, msg| %>
		<%= attr %> : <%= msg %>
	<% end %>
</div>

<%= form_for @todo, url: user_todos_path do |f|%>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :due_date %><br>
  <%= f.date_field :due_date %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<% end %>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

app/views/todos/index.html.erb
<h1>My Todo</h1>
<table>
	<tr>
		<th>Title</th>
		<th>Due date</th>
		<th>Description</th>
		<th colspan="4"></th>
	</tr>
	<% @todos.each do |todo| %>
		<tr>
			<td><%= todo.title %></td>
			<td><%= todo.due_date %></td>
			<td><%= todo.description %></td>
			<td><%= link_to "Up", user_todo_up_url(todo), method: :patch if !todo.is_first %></td>
			<td><%= link_to "Down", user_todo_down_url(todo), method: :patch if !todo.is_last %></td>
			<td><%= link_to "Delete", user_todo_url(todo), method: :delete %></td>
			<td><%= link_to "Done", user_todo_done_url(todo), method: :patch %></td>
		</tr>
	<% end %>
</table>
<br/>
<%= link_to 'New', new_user_todo_path %><br/><br/>
<%= link_to "Sign out", delete_session_path, method: :delete %>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<%= render 'form' %>
<%= link_to "Back", user_todos_url %>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>

app/views/users/_form.html.erb
<div class="error">
	<% @user.errors.each do |attr, msg| %>
		<%= attr %> : <%= msg %>
	<% end %>
</div>

<%= form_for @user do |f|%>
  <%= f.label :email %><br>
  <%= f.email_field :email %><br>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= link_to 'Back', root_path %>
<h1>Sign Up</h1>
<%= render 'form' %>